import "./globals.scss";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

const ubuntu = Roboto({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={ubuntu.className}>
      <body>{children}</body>
    </html>
  );
}
